# Generated by Django 3.2.15 on 2022-08-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('guests', models.PositiveSmallIntegerField()),
                ('date', models.DateTimeField()),
                ('info', models.TextField(max_length=500)),
            ],
        ),
    ]
