# Generated by Django 3.2.15 on 2022-08-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20220818_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guests',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
