# Generated by Django 3.2.15 on 2022-08-19 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_menurestaurant_restaurant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['type']},
        ),
        migrations.DeleteModel(
            name='MenuRestaurant',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
